language: node_js
node_js:
- "6"
- "6.1"
- "6.3"
- 'stable'
services: mongodb
sudo: true
before_script:
- npm install
- npm install -g gulp
- npm install -g typings
- typings install
script:
- gulp compile
- gulp test